# Copyright (C) 2003-2016 CS-SI. All Rights Reserved.
# Author: Nicolas Delon <nicolas.delon@libiodef-ids.com>
#
# This file is part of the LibIodef library.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

package GenerateIODEFMessageWriteC;

use Generate;
@ISA = qw/Generate/;

use strict;
use IODEFTree;

sub        header
{
     my        $self = shift;

     $self->output("
/*****
*
* Copyright (C) 2001-2016 CS-SI. All Rights Reserved.
* Author: Yoann Vandoorselaere <yoann.v\@libiodef-ids.com>
* Author: Nicolas Delon <nicolas.delon\@libiodef-ids.com>
*
* This file is part of the LibIodef library.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*
*****/

/* Auto-generated by the GenerateIODEFMessageWriteC package */

#include \"config.h\"

#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include \"libiodef-inttypes.h\"
#include \"libiodef-list.h\"
#include \"libiodef-log.h\"
#include \"libiodef-io.h\"
#include \"libiodef-ident.h\"
#include \"libiodef-document-id.h\"
#include \"iodef-document-id.h\"
#include \"iodef.h\"
#include \"iodef-tree-wrap.h\"
#include \"iodef-document-write.h\"
#include \"common.h\"



/*
 * If you wonder why we do this, and why life is complicated,
 * then wonder why the hell the guys that wrote IODEF choose to use XML.
 * XML is dog slow. And XML'll never achieve performance needed for real time IDS.
 *
 * Here we are trying to communicate using a home made, binary version of IODEF.
 */

int binary_write(libiodef_io_t *fd, uint8_t tag, uint32_t len, const void *data)
{
        uint32_t l;

        l = htonl(len);

        libiodef_io_write(fd, &tag, sizeof(tag));
        libiodef_io_write(fd, &l, sizeof(l));

        if ( len > 0 )
                libiodef_io_write(fd, data, len);

        return 1;
}


static inline int libiodef_string_write(libiodef_string_t *string, libiodef_io_t *fd, uint8_t tag)
\{
        if ( ! string || libiodef_string_is_empty(string) )
                return 0;

        return binary_write(fd, tag, libiodef_string_get_len(string) + 1, libiodef_string_get_string(string));
\}



static inline int uint64_write(uint64_t data, libiodef_io_t *fd, uint8_t tag)
\{
        uint64_t dst;

        dst = libiodef_hton64(data);

        return binary_write(fd, tag, sizeof(dst), &dst);
\}



static inline int uint32_write(uint32_t data, libiodef_io_t *fd, uint8_t tag)
\{
        data = htonl(data);
        return binary_write(fd, tag, sizeof(data), &data);
\}



static inline int int32_write(uint32_t data, libiodef_io_t *fd, uint8_t tag)
\{
        return uint32_write(data, fd, tag);
\}



static inline int uint8_write(uint8_t data, libiodef_io_t *fd, uint8_t tag)
\{
        return binary_write(fd, tag, sizeof (data), &data);
\}



static inline int uint16_write(uint16_t data, libiodef_io_t *fd, uint8_t tag)
\{
        data = htons(data);
        return binary_write(fd, tag, sizeof(data), &data);
\}



static inline int float_write(float data, libiodef_io_t *fd, uint8_t tag)
\{
        uint32_t tmp = libiodef_htonf(data);
        return binary_write(fd, tag, sizeof(tmp), &tmp);
\}


static inline int iodef_time_write(const iodef_time_t *data, libiodef_io_t *fd, uint8_t tag)
\{
        uint32_t tmp;
        unsigned char buf[12];

        if ( ! data )
                return 0;

        tmp = htonl(iodef_time_get_sec(data));
        memcpy(buf, &tmp, sizeof(tmp));

        tmp = htonl(iodef_time_get_usec(data));
        memcpy(buf + 4, &tmp, sizeof(tmp));

        tmp = htonl(iodef_time_get_gmt_offset(data));
        memcpy(buf + 8, &tmp, sizeof(tmp));

        return binary_write(fd, tag, sizeof (buf), buf);
\}



static inline int iodef_data_write(iodef_data_t *data, libiodef_io_t *fd, uint8_t tag)
\{
        int ret;
        iodef_data_type_t type;

        if ( ! data )
                return 0;

        type = iodef_data_get_type(data);
        if ( type == IODEF_DATA_TYPE_UNKNOWN )
                return 0;

        ret = uint32_write(iodef_data_get_type(data), fd, tag);
        if ( ret < 0 )
                return ret;

        switch ( type ) \{
        case IODEF_DATA_TYPE_CHAR:
        case IODEF_DATA_TYPE_BYTE:
                ret = uint8_write(* (const uint8_t *) iodef_data_get_data(data), fd, tag);
                break;

        case IODEF_DATA_TYPE_UINT32:
                ret = uint32_write(iodef_data_get_int(data), fd, tag);
                break;

        case IODEF_DATA_TYPE_INT:
                ret = uint64_write(iodef_data_get_int(data), fd, tag);
                break;

        case IODEF_DATA_TYPE_FLOAT:
                ret = float_write(iodef_data_get_float(data), fd, tag);
                break;

        case IODEF_DATA_TYPE_CHAR_STRING:
        case IODEF_DATA_TYPE_BYTE_STRING:
                ret = binary_write(fd, tag, iodef_data_get_len(data), iodef_data_get_data(data));
                break;

        case IODEF_DATA_TYPE_TIME:
                ret = iodef_time_write(iodef_data_get_data(data), fd, tag);
                break;

        case IODEF_DATA_TYPE_UNKNOWN:
                /* nop */;
        \}

        return ret;
\}

");
}

sub        struct_field_normal
{
    my        $self = shift;
    my        $tree = shift;
    my        $struct = shift;
    my        $field = shift;
    my        $type = shift || $field->{short_typename};
    my        $function;

    $function = "${type}_write";

    if ( $field->{metatype} & &METATYPE_OPTIONAL_INT ) {
        $self->output("
        {
                $field->{typename} *tmp;

                tmp = iodef_$struct->{short_typename}_get_$field->{name}($struct->{short_typename});
                if ( tmp ) \{
                        ret = $function(*tmp, fd, IODEF_MSG_",  uc($struct->{short_typename}), "_", uc($field->{name}), ");
                        if ( ret < 0 )
                                return ret;");

        $self->output("
                \}
        \}\n");
    } else {
        $self->output(" " x 8,
                      "ret = $function(iodef_$struct->{short_typename}_get_$field->{name}($struct->{short_typename}), ",
                      "fd, IODEF_MSG_",  uc($struct->{short_typename}), "_", uc($field->{name}),
                      ");\n",
                      " " x 8, "if ( ret < 0 )\n",
                      " " x 16, "return ret;\n\n");

    }
}

sub        struct_field_struct
{
    my        $self = shift;
    my        $tree = shift;
    my        $struct = shift;
    my        $field = shift;

    $self->output(" " x 8,
                  "ret = iodef_$field->{short_typename}_write(iodef_$struct->{short_typename}_get_$field->{name}($struct->{short_typename}), fd);\n",
                  " " x 8, "if ( ret < 0 )\n", " " x 16, "return ret;\n");
}

sub        struct_field_list
{
    my        $self = shift;
    my        $tree = shift;
    my        $struct = shift;
    my        $field = shift;

    $self->output("\n");
    $self->output(" " x 8, "{\n");
    $self->output(" " x 16, "$field->{typename} *$field->{short_name} = NULL;", "\n\n");
    $self->output(" " x 16, "while ( ($field->{short_name} = iodef_$struct->{short_typename}_get_next_$field->{short_name}($struct->{short_typename}, $field->{short_name})) ) {", "\n");

    if ( $field->{metatype} & &METATYPE_PRIMITIVE ) {
        $self->output(" " x 24,
                      "ret = $field->{short_typename}_write($field->{short_name}, fd, ",
                      "IODEF_MSG_", uc($struct->{short_typename}), "_", uc($field->{short_name}), ");\n",
                      " " x 24, "if ( ret < 0 )\n", " " x 32, "return ret;\n");

    } else {
        $self->output(" " x 24, "ret = iodef_$field->{short_typename}_write($field->{short_name}, fd);\n",
                      " " x 24, "if ( ret < 0 )\n", " " x 32, "return ret;\n");
    }

    $self->output(" " x 16, "}\n");
    $self->output(" " x 8, "}\n");
    $self->output("\n");
}

sub        struct_field_union
{
    my        $self = shift;
    my        $tree = shift;
    my        $struct = shift;
    my        $field = shift;

    $self->output("\n");
    $self->output(" " x 8, "switch ( iodef_$struct->{short_typename}_get_$field->{var}($struct->{short_typename}) ) {", "\n\n");

    foreach my $member ( @{$field->{member_list}} ) {
        $self->output(" " x 16, "case $member->{value}:", "\n");
        $self->output(" " x 24, "ret = iodef_$member->{short_typename}_write(iodef_$struct->{short_typename}_get_$member->{name}($struct->{short_typename}), fd);", "\n");
        $self->output(" " x 24, "break;", "\n\n");
    }

    $self->output(" " x 16, "default:", "\n",
                  " " x 24, "/* nop */;", "\n\n");
    $self->output(" " x 8, "}\n");
}

sub        pre_declared
{
    my        $self = shift;
    my        $tree = shift;
    my        $struct = shift;

    $self->output("int iodef_$struct->{short_typename}_write($struct->{typename} *, libiodef_io_t *);", "\n\n");
}

sub        struct
{
    my        $self = shift;
    my        $tree = shift;
    my        $struct = shift;

    $self->output("
/**
 * iodef_$struct->{short_typename}_write:
 * \@$struct->{short_typename}: Pointer to a #$struct->{typename} object.
 * \@msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write \@$struct->{short_typename} within \@msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_$struct->{short_typename}_write($struct->{typename} *$struct->{short_typename}, libiodef_io_t *fd)\n\{\n", " " x 8, "int ret;\n");

    $self->output(" " x 8, "if ( ! $struct->{short_typename} )", "\n",
                  " " x 16, "return 0;",
                  "\n\n");

    if ( ! $struct->{toplevel} ) {
        $self->output(" " x 8, "ret = binary_write(fd, ", "IODEF_MSG_" . uc($struct->{short_typename}) . "_TAG", ", 0, NULL);\n",
" " x 8, "if ( ret < 0 )\n", " " x 16, "return ret;\n");
    }

    foreach my $field ( @{ $struct->{field_list} } ) {

        if ( $field->{metatype} & &METATYPE_NORMAL ) {

            if ( $field->{metatype} & &METATYPE_PRIMITIVE ) {
                $self->struct_field_normal($tree, $struct, $field);

            } elsif ( $field->{metatype} & &METATYPE_STRUCT ) {
                $self->struct_field_struct($tree, $struct, $field);

            } elsif ( $field->{metatype} & &METATYPE_ENUM ) {
                $self->struct_field_normal($tree, $struct, $field, "uint32");
            }

        } elsif ( $field->{metatype} & &METATYPE_LIST ) {
            $self->struct_field_list($tree, $struct, $field);

        } elsif ( $field->{metatype} & &METATYPE_UNION ) {
            $self->struct_field_union($tree, $struct, $field);
        }
    }

    $self->output(" " x 8, "return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);\n");
    $self->output("\}\n\n\n");
}

1;
