
/*****
*
* Copyright (C) 2001-2016 CS-SI. All Rights Reserved.
* Author: Yoann Vandoorselaere <yoann.v@libiodef-ids.com>
* Author: Nicolas Delon <nicolas.delon@libiodef-ids.com>
*
* This file is part of the LibIodef library.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*
*****/

/* Auto-generated by the GenerateIODEFMessageWriteC package */

#include "config.h"

#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "libiodef-inttypes.h"
#include "libiodef-list.h"
#include "libiodef-log.h"
#include "libiodef-io.h"
#include "libiodef-ident.h"
#include "libiodef-document-id.h"
#include "iodef-document-id.h"
#include "iodef.h"
#include "iodef-tree-wrap.h"
#include "iodef-document-write.h"
#include "common.h"



/*
 * If you wonder why we do this, and why life is complicated,
 * then wonder why the hell the guys that wrote IODEF choose to use XML.
 * XML is dog slow. And XML'll never achieve performance needed for real time IDS.
 *
 * Here we are trying to communicate using a home made, binary version of IODEF.
 */

int binary_write(libiodef_io_t *fd, uint8_t tag, uint32_t len, const void *data)
{
        uint32_t l;

        l = htonl(len);

        libiodef_io_write(fd, &tag, sizeof(tag));
        libiodef_io_write(fd, &l, sizeof(l));

        if ( len > 0 )
                libiodef_io_write(fd, data, len);

        return 1;
}


static inline int libiodef_string_write(libiodef_string_t *string, libiodef_io_t *fd, uint8_t tag)
{
        if ( ! string || libiodef_string_is_empty(string) )
                return 0;

        return binary_write(fd, tag, libiodef_string_get_len(string) + 1, libiodef_string_get_string(string));
}



static inline int uint64_write(uint64_t data, libiodef_io_t *fd, uint8_t tag)
{
        uint64_t dst;

        dst = libiodef_hton64(data);

        return binary_write(fd, tag, sizeof(dst), &dst);
}



static inline int uint32_write(uint32_t data, libiodef_io_t *fd, uint8_t tag)
{
        data = htonl(data);
        return binary_write(fd, tag, sizeof(data), &data);
}



static inline int int32_write(uint32_t data, libiodef_io_t *fd, uint8_t tag)
{
        return uint32_write(data, fd, tag);
}



static inline int uint8_write(uint8_t data, libiodef_io_t *fd, uint8_t tag)
{
        return binary_write(fd, tag, sizeof (data), &data);
}



static inline int uint16_write(uint16_t data, libiodef_io_t *fd, uint8_t tag)
{
        data = htons(data);
        return binary_write(fd, tag, sizeof(data), &data);
}



static inline int float_write(float data, libiodef_io_t *fd, uint8_t tag)
{
        uint32_t tmp = libiodef_htonf(data);
        return binary_write(fd, tag, sizeof(tmp), &tmp);
}


static inline int iodef_time_write(const iodef_time_t *data, libiodef_io_t *fd, uint8_t tag)
{
        uint32_t tmp;
        unsigned char buf[12];

        if ( ! data )
                return 0;

        tmp = htonl(iodef_time_get_sec(data));
        memcpy(buf, &tmp, sizeof(tmp));

        tmp = htonl(iodef_time_get_usec(data));
        memcpy(buf + 4, &tmp, sizeof(tmp));

        tmp = htonl(iodef_time_get_gmt_offset(data));
        memcpy(buf + 8, &tmp, sizeof(tmp));

        return binary_write(fd, tag, sizeof (buf), buf);
}



static inline int iodef_data_write(iodef_data_t *data, libiodef_io_t *fd, uint8_t tag)
{
        int ret;
        iodef_data_type_t type;

        if ( ! data )
                return 0;

        type = iodef_data_get_type(data);
        if ( type == IODEF_DATA_TYPE_UNKNOWN )
                return 0;

        ret = uint32_write(iodef_data_get_type(data), fd, tag);
        if ( ret < 0 )
                return ret;

        switch ( type ) {
        case IODEF_DATA_TYPE_CHAR:
        case IODEF_DATA_TYPE_BYTE:
                ret = uint8_write(* (const uint8_t *) iodef_data_get_data(data), fd, tag);
                break;

        case IODEF_DATA_TYPE_UINT32:
                ret = uint32_write(iodef_data_get_int(data), fd, tag);
                break;

        case IODEF_DATA_TYPE_INT:
                ret = uint64_write(iodef_data_get_int(data), fd, tag);
                break;

        case IODEF_DATA_TYPE_FLOAT:
                ret = float_write(iodef_data_get_float(data), fd, tag);
                break;

        case IODEF_DATA_TYPE_CHAR_STRING:
        case IODEF_DATA_TYPE_BYTE_STRING:
                ret = binary_write(fd, tag, iodef_data_get_len(data), iodef_data_get_data(data));
                break;

        case IODEF_DATA_TYPE_TIME:
                ret = iodef_time_write(iodef_data_get_data(data), fd, tag);
                break;

        case IODEF_DATA_TYPE_UNKNOWN:
                /* nop */;
        }

        return ret;
}


/**
 * iodef_additional_data_write:
 * @additional_data: Pointer to a #iodef_additional_data_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @additional_data within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_additional_data_write(iodef_additional_data_t *additional_data, libiodef_io_t *fd)
{
        int ret;
        if ( ! additional_data )
                return 0;

        ret = binary_write(fd, IODEF_MSG_ADDITIONAL_DATA_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_additional_data_get_restriction(additional_data), fd, IODEF_MSG_ADDITIONAL_DATA_RESTRICTION);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_additional_data_get_type(additional_data), fd, IODEF_MSG_ADDITIONAL_DATA_TYPE);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_additional_data_get_formatid(additional_data), fd, IODEF_MSG_ADDITIONAL_DATA_FORMATID);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_additional_data_get_meaning(additional_data), fd, IODEF_MSG_ADDITIONAL_DATA_MEANING);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_additional_data_get_ext_dtype(additional_data), fd, IODEF_MSG_ADDITIONAL_DATA_EXT_DTYPE);
        if ( ret < 0 )
                return ret;

        ret = iodef_data_write(iodef_additional_data_get_data(additional_data), fd, IODEF_MSG_ADDITIONAL_DATA_DATA);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_email_write:
 * @email: Pointer to a #iodef_email_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @email within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_email_write(iodef_email_t *email, libiodef_io_t *fd)
{
        int ret;
        if ( ! email )
                return 0;

        ret = binary_write(fd, IODEF_MSG_EMAIL_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_email_get_meaning(email), fd, IODEF_MSG_EMAIL_MEANING);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_email_get_email(email), fd, IODEF_MSG_EMAIL_EMAIL);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_registry_handle_write:
 * @registry_handle: Pointer to a #iodef_registry_handle_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @registry_handle within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_registry_handle_write(iodef_registry_handle_t *registry_handle, libiodef_io_t *fd)
{
        int ret;
        if ( ! registry_handle )
                return 0;

        ret = binary_write(fd, IODEF_MSG_REGISTRY_HANDLE_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_registry_handle_get_registry(registry_handle), fd, IODEF_MSG_REGISTRY_HANDLE_REGISTRY);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_registry_handle_get_ext_registry(registry_handle), fd, IODEF_MSG_REGISTRY_HANDLE_EXT_REGISTRY);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_postal_address_write:
 * @postal_address: Pointer to a #iodef_postal_address_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @postal_address within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_postal_address_write(iodef_postal_address_t *postal_address, libiodef_io_t *fd)
{
        int ret;
        if ( ! postal_address )
                return 0;

        ret = binary_write(fd, IODEF_MSG_POSTAL_ADDRESS_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_postal_address_get_lang(postal_address), fd, IODEF_MSG_POSTAL_ADDRESS_LANG);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_postal_address_get_meaning(postal_address), fd, IODEF_MSG_POSTAL_ADDRESS_MEANING);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_contact_write:
 * @contact: Pointer to a #iodef_contact_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @contact within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_contact_write(iodef_contact_t *contact, libiodef_io_t *fd)
{
        int ret;
        if ( ! contact )
                return 0;

        ret = binary_write(fd, IODEF_MSG_CONTACT_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;

        {
                iodef_additional_data_t *additional_data = NULL;

                while ( (additional_data = iodef_contact_get_next_additional_data(contact, additional_data)) ) {
                        ret = iodef_additional_data_write(additional_data, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = libiodef_string_write(iodef_contact_get_fax(contact), fd, IODEF_MSG_CONTACT_FAX);
        if ( ret < 0 )
                return ret;


        {
                libiodef_string_t *description = NULL;

                while ( (description = iodef_contact_get_next_description(contact, description)) ) {
                        ret = libiodef_string_write(description, fd, IODEF_MSG_CONTACT_DESCRIPTION);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                libiodef_string_t *telephone = NULL;

                while ( (telephone = iodef_contact_get_next_telephone(contact, telephone)) ) {
                        ret = libiodef_string_write(telephone, fd, IODEF_MSG_CONTACT_TELEPHONE);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_registry_handle_t *registry_handle = NULL;

                while ( (registry_handle = iodef_contact_get_next_registry_handle(contact, registry_handle)) ) {
                        ret = iodef_registry_handle_write(registry_handle, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_contact_t *contact = NULL;

                while ( (contact = iodef_contact_get_next_contact(contact, contact)) ) {
                        ret = iodef_contact_write(contact, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = libiodef_string_write(iodef_contact_get_contact_name(contact), fd, IODEF_MSG_CONTACT_CONTACT_NAME);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_contact_get_timezone(contact), fd, IODEF_MSG_CONTACT_TIMEZONE);
        if ( ret < 0 )
                return ret;

        ret = iodef_postal_address_write(iodef_contact_get_postal_address(contact), fd);
        if ( ret < 0 )
                return ret;

        {
                iodef_email_t *email = NULL;

                while ( (email = iodef_contact_get_next_email(contact, email)) ) {
                        ret = iodef_email_write(email, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = uint32_write(iodef_contact_get_type(contact), fd, IODEF_MSG_CONTACT_TYPE);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_contact_get_role(contact), fd, IODEF_MSG_CONTACT_ROLE);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_contact_get_ext_type(contact), fd, IODEF_MSG_CONTACT_EXT_TYPE);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_contact_get_ext_role(contact), fd, IODEF_MSG_CONTACT_EXT_ROLE);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_contact_get_restriction(contact), fd, IODEF_MSG_CONTACT_RESTRICTION);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_incident_id_write:
 * @incident_id: Pointer to a #iodef_incident_id_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @incident_id within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_incident_id_write(iodef_incident_id_t *incident_id, libiodef_io_t *fd)
{
        int ret;
        if ( ! incident_id )
                return 0;

        ret = binary_write(fd, IODEF_MSG_INCIDENT_ID_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = libiodef_string_write(iodef_incident_id_get_instance(incident_id), fd, IODEF_MSG_INCIDENT_ID_INSTANCE);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_incident_id_get_name(incident_id), fd, IODEF_MSG_INCIDENT_ID_NAME);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_incident_id_get_restriction(incident_id), fd, IODEF_MSG_INCIDENT_ID_RESTRICTION);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_alternative_id_write:
 * @alternative_id: Pointer to a #iodef_alternative_id_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @alternative_id within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_alternative_id_write(iodef_alternative_id_t *alternative_id, libiodef_io_t *fd)
{
        int ret;
        if ( ! alternative_id )
                return 0;

        ret = binary_write(fd, IODEF_MSG_ALTERNATIVE_ID_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;

        {
                iodef_incident_id_t *incident_id = NULL;

                while ( (incident_id = iodef_alternative_id_get_next_incident_id(alternative_id, incident_id)) ) {
                        ret = iodef_incident_id_write(incident_id, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = uint32_write(iodef_alternative_id_get_restriction(alternative_id), fd, IODEF_MSG_ALTERNATIVE_ID_RESTRICTION);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_related_activity_write:
 * @related_activity: Pointer to a #iodef_related_activity_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @related_activity within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_related_activity_write(iodef_related_activity_t *related_activity, libiodef_io_t *fd)
{
        int ret;
        if ( ! related_activity )
                return 0;

        ret = binary_write(fd, IODEF_MSG_RELATED_ACTIVITY_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;

        {
                libiodef_string_t *url = NULL;

                while ( (url = iodef_related_activity_get_next_url(related_activity, url)) ) {
                        ret = libiodef_string_write(url, fd, IODEF_MSG_RELATED_ACTIVITY_URL);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_incident_id_t *incident_id = NULL;

                while ( (incident_id = iodef_related_activity_get_next_incident_id(related_activity, incident_id)) ) {
                        ret = iodef_incident_id_write(incident_id, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = uint32_write(iodef_related_activity_get_restriction(related_activity), fd, IODEF_MSG_RELATED_ACTIVITY_RESTRICTION);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_history_item_write:
 * @history_item: Pointer to a #iodef_history_item_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @history_item within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_history_item_write(iodef_history_item_t *history_item, libiodef_io_t *fd)
{
        int ret;
        if ( ! history_item )
                return 0;

        ret = binary_write(fd, IODEF_MSG_HISTORY_ITEM_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;

        {
                iodef_additional_data_t *additional_data = NULL;

                while ( (additional_data = iodef_history_item_get_next_additional_data(history_item, additional_data)) ) {
                        ret = iodef_additional_data_write(additional_data, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_incident_id_write(iodef_history_item_get_incident_id(history_item), fd);
        if ( ret < 0 )
                return ret;

        {
                libiodef_string_t *description = NULL;

                while ( (description = iodef_history_item_get_next_description(history_item, description)) ) {
                        ret = libiodef_string_write(description, fd, IODEF_MSG_HISTORY_ITEM_DESCRIPTION);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_contact_write(iodef_history_item_get_contact(history_item), fd);
        if ( ret < 0 )
                return ret;
        ret = iodef_time_write(iodef_history_item_get_date_time(history_item), fd, IODEF_MSG_HISTORY_ITEM_DATE_TIME);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_history_item_get_action(history_item), fd, IODEF_MSG_HISTORY_ITEM_ACTION);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_history_item_get_restriction(history_item), fd, IODEF_MSG_HISTORY_ITEM_RESTRICTION);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_history_item_get_ext_action(history_item), fd, IODEF_MSG_HISTORY_ITEM_EXT_ACTION);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_history_write:
 * @history: Pointer to a #iodef_history_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @history within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_history_write(iodef_history_t *history, libiodef_io_t *fd)
{
        int ret;
        if ( ! history )
                return 0;

        ret = binary_write(fd, IODEF_MSG_HISTORY_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;

        {
                iodef_history_item_t *history_item = NULL;

                while ( (history_item = iodef_history_get_next_history_item(history, history_item)) ) {
                        ret = iodef_history_item_write(history_item, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = uint32_write(iodef_history_get_restriction(history), fd, IODEF_MSG_HISTORY_RESTRICTION);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_expectation_write:
 * @expectation: Pointer to a #iodef_expectation_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @expectation within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_expectation_write(iodef_expectation_t *expectation, libiodef_io_t *fd)
{
        int ret;
        if ( ! expectation )
                return 0;

        ret = binary_write(fd, IODEF_MSG_EXPECTATION_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = iodef_time_write(iodef_expectation_get_end_time(expectation), fd, IODEF_MSG_EXPECTATION_END_TIME);
        if ( ret < 0 )
                return ret;


        {
                libiodef_string_t *description = NULL;

                while ( (description = iodef_expectation_get_next_description(expectation, description)) ) {
                        ret = libiodef_string_write(description, fd, IODEF_MSG_EXPECTATION_DESCRIPTION);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_time_write(iodef_expectation_get_start_time(expectation), fd, IODEF_MSG_EXPECTATION_START_TIME);
        if ( ret < 0 )
                return ret;

        ret = iodef_contact_write(iodef_expectation_get_contact(expectation), fd);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_expectation_get_action(expectation), fd, IODEF_MSG_EXPECTATION_ACTION);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_expectation_get_restriction(expectation), fd, IODEF_MSG_EXPECTATION_RESTRICTION);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_expectation_get_ext_action(expectation), fd, IODEF_MSG_EXPECTATION_EXT_ACTION);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_expectation_get_severity(expectation), fd, IODEF_MSG_EXPECTATION_SEVERITY);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_record_pattern_write:
 * @record_pattern: Pointer to a #iodef_record_pattern_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @record_pattern within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_record_pattern_write(iodef_record_pattern_t *record_pattern, libiodef_io_t *fd)
{
        int ret;
        if ( ! record_pattern )
                return 0;

        ret = binary_write(fd, IODEF_MSG_RECORD_PATTERN_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_record_pattern_get_offsetunit(record_pattern), fd, IODEF_MSG_RECORD_PATTERN_OFFSETUNIT);
        if ( ret < 0 )
                return ret;


        {
                uint32_t *tmp;

                tmp = iodef_record_pattern_get_instance(record_pattern);
                if ( tmp ) {
                        ret = uint32_write(*tmp, fd, IODEF_MSG_RECORD_PATTERN_INSTANCE);
                        if ( ret < 0 )
                                return ret;
                }
        }
        ret = libiodef_string_write(iodef_record_pattern_get_ext_type(record_pattern), fd, IODEF_MSG_RECORD_PATTERN_EXT_TYPE);
        if ( ret < 0 )
                return ret;


        {
                uint32_t *tmp;

                tmp = iodef_record_pattern_get_offset(record_pattern);
                if ( tmp ) {
                        ret = uint32_write(*tmp, fd, IODEF_MSG_RECORD_PATTERN_OFFSET);
                        if ( ret < 0 )
                                return ret;
                }
        }
        ret = libiodef_string_write(iodef_record_pattern_get_ext_offsetunit(record_pattern), fd, IODEF_MSG_RECORD_PATTERN_EXT_OFFSETUNIT);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_record_pattern_get_type(record_pattern), fd, IODEF_MSG_RECORD_PATTERN_TYPE);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_record_item_write:
 * @record_item: Pointer to a #iodef_record_item_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @record_item within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_record_item_write(iodef_record_item_t *record_item, libiodef_io_t *fd)
{
        int ret;
        if ( ! record_item )
                return 0;

        ret = binary_write(fd, IODEF_MSG_RECORD_ITEM_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_record_item_get_restriction(record_item), fd, IODEF_MSG_RECORD_ITEM_RESTRICTION);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_record_item_get_dtype(record_item), fd, IODEF_MSG_RECORD_ITEM_DTYPE);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_record_item_get_formatid(record_item), fd, IODEF_MSG_RECORD_ITEM_FORMATID);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_record_item_get_meaning(record_item), fd, IODEF_MSG_RECORD_ITEM_MEANING);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_record_item_get_ext_dtype(record_item), fd, IODEF_MSG_RECORD_ITEM_EXT_DTYPE);
        if ( ret < 0 )
                return ret;

        ret = iodef_data_write(iodef_record_item_get_data(record_item), fd, IODEF_MSG_RECORD_ITEM_DATA);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_application_write:
 * @application: Pointer to a #iodef_application_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @application within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_application_write(iodef_application_t *application, libiodef_io_t *fd)
{
        int ret;
        if ( ! application )
                return 0;

        ret = binary_write(fd, IODEF_MSG_APPLICATION_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = libiodef_string_write(iodef_application_get_url(application), fd, IODEF_MSG_APPLICATION_URL);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_application_get_vendor(application), fd, IODEF_MSG_APPLICATION_VENDOR);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_application_get_name(application), fd, IODEF_MSG_APPLICATION_NAME);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_application_get_family(application), fd, IODEF_MSG_APPLICATION_FAMILY);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_application_get_swid(application), fd, IODEF_MSG_APPLICATION_SWID);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_application_get_patch(application), fd, IODEF_MSG_APPLICATION_PATCH);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_application_get_version(application), fd, IODEF_MSG_APPLICATION_VERSION);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_application_get_configid(application), fd, IODEF_MSG_APPLICATION_CONFIGID);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_record_data_write:
 * @record_data: Pointer to a #iodef_record_data_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @record_data within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_record_data_write(iodef_record_data_t *record_data, libiodef_io_t *fd)
{
        int ret;
        if ( ! record_data )
                return 0;

        ret = binary_write(fd, IODEF_MSG_RECORD_DATA_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = iodef_additional_data_write(iodef_record_data_get_additional_data(record_data), fd);
        if ( ret < 0 )
                return ret;

        {
                libiodef_string_t *description = NULL;

                while ( (description = iodef_record_data_get_next_description(record_data, description)) ) {
                        ret = libiodef_string_write(description, fd, IODEF_MSG_RECORD_DATA_DESCRIPTION);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_record_pattern_t *record_pattern = NULL;

                while ( (record_pattern = iodef_record_data_get_next_record_pattern(record_data, record_pattern)) ) {
                        ret = iodef_record_pattern_write(record_pattern, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_time_write(iodef_record_data_get_date_time(record_data), fd, IODEF_MSG_RECORD_DATA_DATE_TIME);
        if ( ret < 0 )
                return ret;

        ret = iodef_application_write(iodef_record_data_get_application(record_data), fd);
        if ( ret < 0 )
                return ret;

        {
                iodef_record_item_t *record_item = NULL;

                while ( (record_item = iodef_record_data_get_next_record_item(record_data, record_item)) ) {
                        ret = iodef_record_item_write(record_item, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = uint32_write(iodef_record_data_get_restriction(record_data), fd, IODEF_MSG_RECORD_DATA_RESTRICTION);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_record_write:
 * @record: Pointer to a #iodef_record_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @record within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_record_write(iodef_record_t *record, libiodef_io_t *fd)
{
        int ret;
        if ( ! record )
                return 0;

        ret = binary_write(fd, IODEF_MSG_RECORD_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;

        {
                iodef_record_data_t *record_data = NULL;

                while ( (record_data = iodef_record_get_next_record_data(record, record_data)) ) {
                        ret = iodef_record_data_write(record_data, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = uint32_write(iodef_record_get_restriction(record), fd, IODEF_MSG_RECORD_RESTRICTION);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_reference_write:
 * @reference: Pointer to a #iodef_reference_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @reference within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_reference_write(iodef_reference_t *reference, libiodef_io_t *fd)
{
        int ret;
        if ( ! reference )
                return 0;

        ret = binary_write(fd, IODEF_MSG_REFERENCE_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;

        {
                libiodef_string_t *url = NULL;

                while ( (url = iodef_reference_get_next_url(reference, url)) ) {
                        ret = libiodef_string_write(url, fd, IODEF_MSG_REFERENCE_URL);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                libiodef_string_t *description = NULL;

                while ( (description = iodef_reference_get_next_description(reference, description)) ) {
                        ret = libiodef_string_write(description, fd, IODEF_MSG_REFERENCE_DESCRIPTION);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = libiodef_string_write(iodef_reference_get_reference_name(reference), fd, IODEF_MSG_REFERENCE_REFERENCE_NAME);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_method_write:
 * @method: Pointer to a #iodef_method_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @method within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_method_write(iodef_method_t *method, libiodef_io_t *fd)
{
        int ret;
        if ( ! method )
                return 0;

        ret = binary_write(fd, IODEF_MSG_METHOD_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;

        {
                iodef_additional_data_t *additional_data = NULL;

                while ( (additional_data = iodef_method_get_next_additional_data(method, additional_data)) ) {
                        ret = iodef_additional_data_write(additional_data, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                libiodef_string_t *description = NULL;

                while ( (description = iodef_method_get_next_description(method, description)) ) {
                        ret = libiodef_string_write(description, fd, IODEF_MSG_METHOD_DESCRIPTION);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_reference_t *reference = NULL;

                while ( (reference = iodef_method_get_next_reference(method, reference)) ) {
                        ret = iodef_reference_write(reference, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = uint32_write(iodef_method_get_restriction(method), fd, IODEF_MSG_METHOD_RESTRICTION);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_time_impact_write:
 * @time_impact: Pointer to a #iodef_time_impact_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @time_impact within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_time_impact_write(iodef_time_impact_t *time_impact, libiodef_io_t *fd)
{
        int ret;
        if ( ! time_impact )
                return 0;

        ret = binary_write(fd, IODEF_MSG_TIME_IMPACT_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = libiodef_string_write(iodef_time_impact_get_ext_metric(time_impact), fd, IODEF_MSG_TIME_IMPACT_EXT_METRIC);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_time_impact_get_duration(time_impact), fd, IODEF_MSG_TIME_IMPACT_DURATION);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_time_impact_get_metric(time_impact), fd, IODEF_MSG_TIME_IMPACT_METRIC);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_time_impact_get_severity(time_impact), fd, IODEF_MSG_TIME_IMPACT_SEVERITY);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_time_impact_get_ext_duration(time_impact), fd, IODEF_MSG_TIME_IMPACT_EXT_DURATION);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_impact_write:
 * @impact: Pointer to a #iodef_impact_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @impact within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_impact_write(iodef_impact_t *impact, libiodef_io_t *fd)
{
        int ret;
        if ( ! impact )
                return 0;

        ret = binary_write(fd, IODEF_MSG_IMPACT_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_impact_get_lang(impact), fd, IODEF_MSG_IMPACT_LANG);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_impact_get_completion(impact), fd, IODEF_MSG_IMPACT_COMPLETION);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_impact_get_type(impact), fd, IODEF_MSG_IMPACT_TYPE);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_impact_get_severity(impact), fd, IODEF_MSG_IMPACT_SEVERITY);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_impact_get_ext_type(impact), fd, IODEF_MSG_IMPACT_EXT_TYPE);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_confidence_write:
 * @confidence: Pointer to a #iodef_confidence_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @confidence within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_confidence_write(iodef_confidence_t *confidence, libiodef_io_t *fd)
{
        int ret;
        if ( ! confidence )
                return 0;

        ret = binary_write(fd, IODEF_MSG_CONFIDENCE_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_confidence_get_rating(confidence), fd, IODEF_MSG_CONFIDENCE_RATING);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_monetary_impact_write:
 * @monetary_impact: Pointer to a #iodef_monetary_impact_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @monetary_impact within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_monetary_impact_write(iodef_monetary_impact_t *monetary_impact, libiodef_io_t *fd)
{
        int ret;
        if ( ! monetary_impact )
                return 0;

        ret = binary_write(fd, IODEF_MSG_MONETARY_IMPACT_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = libiodef_string_write(iodef_monetary_impact_get_currency(monetary_impact), fd, IODEF_MSG_MONETARY_IMPACT_CURRENCY);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_monetary_impact_get_severity(monetary_impact), fd, IODEF_MSG_MONETARY_IMPACT_SEVERITY);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_counter_write:
 * @counter: Pointer to a #iodef_counter_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @counter within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_counter_write(iodef_counter_t *counter, libiodef_io_t *fd)
{
        int ret;
        if ( ! counter )
                return 0;

        ret = binary_write(fd, IODEF_MSG_COUNTER_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_counter_get_duration(counter), fd, IODEF_MSG_COUNTER_DURATION);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_counter_get_type(counter), fd, IODEF_MSG_COUNTER_TYPE);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_counter_get_ext_duration(counter), fd, IODEF_MSG_COUNTER_EXT_DURATION);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_counter_get_ext_type(counter), fd, IODEF_MSG_COUNTER_EXT_TYPE);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_assessment_write:
 * @assessment: Pointer to a #iodef_assessment_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @assessment within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_assessment_write(iodef_assessment_t *assessment, libiodef_io_t *fd)
{
        int ret;
        if ( ! assessment )
                return 0;

        ret = binary_write(fd, IODEF_MSG_ASSESSMENT_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;

        {
                iodef_impact_t *impact = NULL;

                while ( (impact = iodef_assessment_get_next_impact(assessment, impact)) ) {
                        ret = iodef_impact_write(impact, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_additional_data_t *additional_data = NULL;

                while ( (additional_data = iodef_assessment_get_next_additional_data(assessment, additional_data)) ) {
                        ret = iodef_additional_data_write(additional_data, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_confidence_write(iodef_assessment_get_confidence(assessment), fd);
        if ( ret < 0 )
                return ret;

        {
                iodef_time_impact_t *time_impact = NULL;

                while ( (time_impact = iodef_assessment_get_next_time_impact(assessment, time_impact)) ) {
                        ret = iodef_time_impact_write(time_impact, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_monetary_impact_t *monetary_impact = NULL;

                while ( (monetary_impact = iodef_assessment_get_next_monetary_impact(assessment, monetary_impact)) ) {
                        ret = iodef_monetary_impact_write(monetary_impact, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_counter_t *counter = NULL;

                while ( (counter = iodef_assessment_get_next_counter(assessment, counter)) ) {
                        ret = iodef_counter_write(counter, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = uint32_write(iodef_assessment_get_restriction(assessment), fd, IODEF_MSG_ASSESSMENT_RESTRICTION);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_assessment_get_occurrence(assessment), fd, IODEF_MSG_ASSESSMENT_OCCURRENCE);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_service_write:
 * @service: Pointer to a #iodef_service_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @service within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_service_write(iodef_service_t *service, libiodef_io_t *fd)
{
        int ret;
        if ( ! service )
                return 0;

        ret = binary_write(fd, IODEF_MSG_SERVICE_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;

        {
                uint32_t *tmp;

                tmp = iodef_service_get_proto_code(service);
                if ( tmp ) {
                        ret = uint32_write(*tmp, fd, IODEF_MSG_SERVICE_PROTO_CODE);
                        if ( ret < 0 )
                                return ret;
                }
        }

        {
                uint32_t *tmp;

                tmp = iodef_service_get_proto_flags(service);
                if ( tmp ) {
                        ret = uint32_write(*tmp, fd, IODEF_MSG_SERVICE_PROTO_FLAGS);
                        if ( ret < 0 )
                                return ret;
                }
        }
        ret = libiodef_string_write(iodef_service_get_portlist(service), fd, IODEF_MSG_SERVICE_PORTLIST);
        if ( ret < 0 )
                return ret;


        {
                iodef_application_t *application = NULL;

                while ( (application = iodef_service_get_next_application(service, application)) ) {
                        ret = iodef_application_write(application, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                uint32_t *tmp;

                tmp = iodef_service_get_proto_type(service);
                if ( tmp ) {
                        ret = uint32_write(*tmp, fd, IODEF_MSG_SERVICE_PROTO_TYPE);
                        if ( ret < 0 )
                                return ret;
                }
        }

        {
                uint32_t *tmp;

                tmp = iodef_service_get_port(service);
                if ( tmp ) {
                        ret = uint32_write(*tmp, fd, IODEF_MSG_SERVICE_PORT);
                        if ( ret < 0 )
                                return ret;
                }
        }

        {
                uint32_t *tmp;

                tmp = iodef_service_get_ip_protocol(service);
                if ( tmp ) {
                        ret = uint32_write(*tmp, fd, IODEF_MSG_SERVICE_IP_PROTOCOL);
                        if ( ret < 0 )
                                return ret;
                }
        }
        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_address_write:
 * @address: Pointer to a #iodef_address_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @address within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_address_write(iodef_address_t *address, libiodef_io_t *fd)
{
        int ret;
        if ( ! address )
                return 0;

        ret = binary_write(fd, IODEF_MSG_ADDRESS_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_address_get_category(address), fd, IODEF_MSG_ADDRESS_CATEGORY);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_address_get_vlan_name(address), fd, IODEF_MSG_ADDRESS_VLAN_NAME);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_address_get_ext_category(address), fd, IODEF_MSG_ADDRESS_EXT_CATEGORY);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_address_get_vlan_num(address), fd, IODEF_MSG_ADDRESS_VLAN_NUM);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_node_role_write:
 * @node_role: Pointer to a #iodef_node_role_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @node_role within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_node_role_write(iodef_node_role_t *node_role, libiodef_io_t *fd)
{
        int ret;
        if ( ! node_role )
                return 0;

        ret = binary_write(fd, IODEF_MSG_NODE_ROLE_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_node_role_get_category(node_role), fd, IODEF_MSG_NODE_ROLE_CATEGORY);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_node_role_get_lang(node_role), fd, IODEF_MSG_NODE_ROLE_LANG);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_node_role_get_ext_category(node_role), fd, IODEF_MSG_NODE_ROLE_EXT_CATEGORY);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_node_write:
 * @node: Pointer to a #iodef_node_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @node within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_node_write(iodef_node_t *node, libiodef_io_t *fd)
{
        int ret;
        if ( ! node )
                return 0;

        ret = binary_write(fd, IODEF_MSG_NODE_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;

        {
                libiodef_string_t *node_name = NULL;

                while ( (node_name = iodef_node_get_next_node_name(node, node_name)) ) {
                        ret = libiodef_string_write(node_name, fd, IODEF_MSG_NODE_NODE_NAME);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_counter_t *counter = NULL;

                while ( (counter = iodef_node_get_next_counter(node, counter)) ) {
                        ret = iodef_counter_write(counter, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_time_write(iodef_node_get_date_time(node), fd, IODEF_MSG_NODE_DATE_TIME);
        if ( ret < 0 )
                return ret;


        {
                iodef_node_role_t *node_role = NULL;

                while ( (node_role = iodef_node_get_next_node_role(node, node_role)) ) {
                        ret = iodef_node_role_write(node_role, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = libiodef_string_write(iodef_node_get_location(node), fd, IODEF_MSG_NODE_LOCATION);
        if ( ret < 0 )
                return ret;


        {
                iodef_address_t *address = NULL;

                while ( (address = iodef_node_get_next_address(node, address)) ) {
                        ret = iodef_address_write(address, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_operating_system_write:
 * @operating_system: Pointer to a #iodef_operating_system_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @operating_system within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_operating_system_write(iodef_operating_system_t *operating_system, libiodef_io_t *fd)
{
        int ret;
        if ( ! operating_system )
                return 0;

        ret = binary_write(fd, IODEF_MSG_OPERATING_SYSTEM_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = libiodef_string_write(iodef_operating_system_get_url(operating_system), fd, IODEF_MSG_OPERATING_SYSTEM_URL);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_operating_system_get_vendor(operating_system), fd, IODEF_MSG_OPERATING_SYSTEM_VENDOR);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_operating_system_get_name(operating_system), fd, IODEF_MSG_OPERATING_SYSTEM_NAME);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_operating_system_get_family(operating_system), fd, IODEF_MSG_OPERATING_SYSTEM_FAMILY);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_operating_system_get_swid(operating_system), fd, IODEF_MSG_OPERATING_SYSTEM_SWID);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_operating_system_get_patch(operating_system), fd, IODEF_MSG_OPERATING_SYSTEM_PATCH);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_operating_system_get_version(operating_system), fd, IODEF_MSG_OPERATING_SYSTEM_VERSION);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_operating_system_get_configid(operating_system), fd, IODEF_MSG_OPERATING_SYSTEM_CONFIGID);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_system_write:
 * @system: Pointer to a #iodef_system_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @system within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_system_write(iodef_system_t *system, libiodef_io_t *fd)
{
        int ret;
        if ( ! system )
                return 0;

        ret = binary_write(fd, IODEF_MSG_SYSTEM_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = iodef_node_write(iodef_system_get_node(system), fd);
        if ( ret < 0 )
                return ret;

        {
                iodef_additional_data_t *additional_data = NULL;

                while ( (additional_data = iodef_system_get_next_additional_data(system, additional_data)) ) {
                        ret = iodef_additional_data_write(additional_data, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                libiodef_string_t *description = NULL;

                while ( (description = iodef_system_get_next_description(system, description)) ) {
                        ret = libiodef_string_write(description, fd, IODEF_MSG_SYSTEM_DESCRIPTION);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_service_t *service = NULL;

                while ( (service = iodef_system_get_next_service(system, service)) ) {
                        ret = iodef_service_write(service, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_counter_t *counter = NULL;

                while ( (counter = iodef_system_get_next_counter(system, counter)) ) {
                        ret = iodef_counter_write(counter, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_operating_system_write(iodef_system_get_operating_system(system), fd);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_system_get_category(system), fd, IODEF_MSG_SYSTEM_CATEGORY);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_system_get_restriction(system), fd, IODEF_MSG_SYSTEM_RESTRICTION);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_system_get_ext_category(system), fd, IODEF_MSG_SYSTEM_EXT_CATEGORY);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_system_get_spoofed(system), fd, IODEF_MSG_SYSTEM_SPOOFED);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_system_get_interface(system), fd, IODEF_MSG_SYSTEM_INTERFACE);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_flow_write:
 * @flow: Pointer to a #iodef_flow_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @flow within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_flow_write(iodef_flow_t *flow, libiodef_io_t *fd)
{
        int ret;
        if ( ! flow )
                return 0;

        ret = binary_write(fd, IODEF_MSG_FLOW_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;

        {
                iodef_system_t *system = NULL;

                while ( (system = iodef_flow_get_next_system(flow, system)) ) {
                        ret = iodef_system_write(system, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_event_data_write:
 * @event_data: Pointer to a #iodef_event_data_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @event_data within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_event_data_write(iodef_event_data_t *event_data, libiodef_io_t *fd)
{
        int ret;
        if ( ! event_data )
                return 0;

        ret = binary_write(fd, IODEF_MSG_EVENT_DATA_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = iodef_time_write(iodef_event_data_get_detect_time(event_data), fd, IODEF_MSG_EVENT_DATA_DETECT_TIME);
        if ( ret < 0 )
                return ret;


        {
                iodef_additional_data_t *additional_data = NULL;

                while ( (additional_data = iodef_event_data_get_next_additional_data(event_data, additional_data)) ) {
                        ret = iodef_additional_data_write(additional_data, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                libiodef_string_t *description = NULL;

                while ( (description = iodef_event_data_get_next_description(event_data, description)) ) {
                        ret = libiodef_string_write(description, fd, IODEF_MSG_EVENT_DATA_DESCRIPTION);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_flow_t *flow = NULL;

                while ( (flow = iodef_event_data_get_next_flow(event_data, flow)) ) {
                        ret = iodef_flow_write(flow, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_expectation_t *expectation = NULL;

                while ( (expectation = iodef_event_data_get_next_expectation(event_data, expectation)) ) {
                        ret = iodef_expectation_write(expectation, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_record_write(iodef_event_data_get_record(event_data), fd);
        if ( ret < 0 )
                return ret;

        {
                iodef_contact_t *contact = NULL;

                while ( (contact = iodef_event_data_get_next_contact(event_data, contact)) ) {
                        ret = iodef_contact_write(contact, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_time_write(iodef_event_data_get_start_time(event_data), fd, IODEF_MSG_EVENT_DATA_START_TIME);
        if ( ret < 0 )
                return ret;


        {
                iodef_event_data_t *event_data = NULL;

                while ( (event_data = iodef_event_data_get_next_event_data(event_data, event_data)) ) {
                        ret = iodef_event_data_write(event_data, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_time_write(iodef_event_data_get_end_time(event_data), fd, IODEF_MSG_EVENT_DATA_END_TIME);
        if ( ret < 0 )
                return ret;

        ret = iodef_assessment_write(iodef_event_data_get_assessment(event_data), fd);
        if ( ret < 0 )
                return ret;

        {
                iodef_method_t *method = NULL;

                while ( (method = iodef_event_data_get_next_method(event_data, method)) ) {
                        ret = iodef_method_write(method, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = uint32_write(iodef_event_data_get_restriction(event_data), fd, IODEF_MSG_EVENT_DATA_RESTRICTION);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_incident_write:
 * @incident: Pointer to a #iodef_incident_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @incident within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_incident_write(iodef_incident_t *incident, libiodef_io_t *fd)
{
        int ret;
        if ( ! incident )
                return 0;

        ret = binary_write(fd, IODEF_MSG_INCIDENT_TAG, 0, NULL);
        if ( ret < 0 )
                return ret;
        ret = iodef_time_write(iodef_incident_get_detect_time(incident), fd, IODEF_MSG_INCIDENT_DETECT_TIME);
        if ( ret < 0 )
                return ret;


        {
                iodef_additional_data_t *additional_data = NULL;

                while ( (additional_data = iodef_incident_get_next_additional_data(incident, additional_data)) ) {
                        ret = iodef_additional_data_write(additional_data, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_time_write(iodef_incident_get_end_time(incident), fd, IODEF_MSG_INCIDENT_END_TIME);
        if ( ret < 0 )
                return ret;


        {
                libiodef_string_t *description = NULL;

                while ( (description = iodef_incident_get_next_description(incident, description)) ) {
                        ret = libiodef_string_write(description, fd, IODEF_MSG_INCIDENT_DESCRIPTION);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_contact_t *contact = NULL;

                while ( (contact = iodef_incident_get_next_contact(incident, contact)) ) {
                        ret = iodef_contact_write(contact, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_alternative_id_write(iodef_incident_get_alternative_id(incident), fd);
        if ( ret < 0 )
                return ret;
        ret = iodef_time_write(iodef_incident_get_report_time(incident), fd, IODEF_MSG_INCIDENT_REPORT_TIME);
        if ( ret < 0 )
                return ret;

        ret = iodef_time_write(iodef_incident_get_start_time(incident), fd, IODEF_MSG_INCIDENT_START_TIME);
        if ( ret < 0 )
                return ret;


        {
                iodef_event_data_t *event_data = NULL;

                while ( (event_data = iodef_incident_get_next_event_data(incident, event_data)) ) {
                        ret = iodef_event_data_write(event_data, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_related_activity_write(iodef_incident_get_related_activity(incident), fd);
        if ( ret < 0 )
                return ret;
        ret = iodef_incident_id_write(iodef_incident_get_incident_id(incident), fd);
        if ( ret < 0 )
                return ret;

        {
                iodef_assessment_t *assessment = NULL;

                while ( (assessment = iodef_incident_get_next_assessment(incident, assessment)) ) {
                        ret = iodef_assessment_write(assessment, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }


        {
                iodef_method_t *method = NULL;

                while ( (method = iodef_incident_get_next_method(incident, method)) ) {
                        ret = iodef_method_write(method, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = iodef_history_write(iodef_incident_get_history(incident), fd);
        if ( ret < 0 )
                return ret;
        ret = uint32_write(iodef_incident_get_lang(incident), fd, IODEF_MSG_INCIDENT_LANG);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_incident_get_restriction(incident), fd, IODEF_MSG_INCIDENT_RESTRICTION);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_incident_get_ext_purpose(incident), fd, IODEF_MSG_INCIDENT_EXT_PURPOSE);
        if ( ret < 0 )
                return ret;

        ret = uint32_write(iodef_incident_get_purpose(incident), fd, IODEF_MSG_INCIDENT_PURPOSE);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}



/**
 * iodef_document_write:
 * @document: Pointer to a #iodef_document_t object.
 * @msg: Pointer to a #libiodef_msgbuf_t object, where the message should be written.
 *
 * Write @document within @msg message buffer. The buffer is
 * associated with a #libiodef_io_t file descriptor where the data will be written.
 *
 * Returns: 0 on success, a negative value if an error occured.
 */
int iodef_document_write(iodef_document_t *document, libiodef_io_t *fd)
{
        int ret;
        if ( ! document )
                return 0;


        {
                iodef_incident_t *incident = NULL;

                while ( (incident = iodef_document_get_next_incident(document, incident)) ) {
                        ret = iodef_incident_write(incident, fd);
                        if ( ret < 0 )
                                return ret;
                }
        }

        ret = uint32_write(iodef_document_get_lang(document), fd, IODEF_MSG_DOCUMENT_LANG);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_document_get_formatid(document), fd, IODEF_MSG_DOCUMENT_FORMATID);
        if ( ret < 0 )
                return ret;

        ret = libiodef_string_write(iodef_document_get_version(document), fd, IODEF_MSG_DOCUMENT_VERSION);
        if ( ret < 0 )
                return ret;

        return binary_write(fd, IODEF_MSG_END_OF_TAG, 0, NULL);
}


