
/* Auto-generated by the GenerateIODEFTreeData package */

typedef struct {
        const char *name;
        prelude_bool_t list;
        prelude_bool_t keyed_list;
        iodef_value_type_id_t type;
        iodef_class_id_t class;
        int union_id;
} children_list_t;

const children_list_t iodef_additional_data_children_list[] = {
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_ADDITIONAL_DATA_RESTRICTION, 0 },
        { "type", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_ADDITIONAL_DATA_TYPE, 0 },
        { "formatid", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "meaning", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "ext_dtype", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "data", 0, 0, IODEF_VALUE_TYPE_DATA, 0, 0 },
};

const children_list_t iodef_email_children_list[] = {
        { "meaning", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_EMAIL_MEANING, 0 },
        { "email", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};

const children_list_t iodef_registry_handle_children_list[] = {
        { "registry", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_REGISTRY_HANDLE_REGISTRY, 0 },
        { "ext_registry", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};

const children_list_t iodef_postal_address_children_list[] = {
        { "lang", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_POSTAL_ADDRESS_LANG, 0 },
        { "meaning", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_POSTAL_ADDRESS_MEANING, 0 },
};

const children_list_t iodef_contact_children_list[] = {
        { "additional_data", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_ADDITIONAL_DATA, 0 },
        { "fax", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "description", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "telephone", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "registry_handle", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_REGISTRY_HANDLE, 0 },
        { "contact", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_CONTACT, 0 },
        { "contact_name", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "timezone", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "postal_address", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_POSTAL_ADDRESS, 0 },
        { "email", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_EMAIL, 0 },
        { "type", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_CONTACT_TYPE, 0 },
        { "role", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_CONTACT_ROLE, 0 },
        { "ext_type", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "ext_role", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_CONTACT_RESTRICTION, 0 },
};

const children_list_t iodef_incident_id_children_list[] = {
        { "instance", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "name", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_INCIDENT_ID_RESTRICTION, 0 },
};

const children_list_t iodef_alternative_id_children_list[] = {
        { "incident_id", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_INCIDENT_ID, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_ALTERNATIVE_ID_RESTRICTION, 0 },
};

const children_list_t iodef_related_activity_children_list[] = {
        { "url", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "incident_id", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_INCIDENT_ID, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_RELATED_ACTIVITY_RESTRICTION, 0 },
};

const children_list_t iodef_history_item_children_list[] = {
        { "additional_data", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_ADDITIONAL_DATA, 0 },
        { "incident_id", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_INCIDENT_ID, 0 },
        { "description", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "contact", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_CONTACT, 0 },
        { "date_time", 0, 0, IODEF_VALUE_TYPE_TIME, 0, 0 },
        { "action", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_HISTORY_ITEM_ACTION, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_HISTORY_ITEM_RESTRICTION, 0 },
        { "ext_action", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};

const children_list_t iodef_history_children_list[] = {
        { "history_item", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_HISTORY_ITEM, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_HISTORY_RESTRICTION, 0 },
};

const children_list_t iodef_expectation_children_list[] = {
        { "end_time", 0, 0, IODEF_VALUE_TYPE_TIME, 0, 0 },
        { "description", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "start_time", 0, 0, IODEF_VALUE_TYPE_TIME, 0, 0 },
        { "contact", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_CONTACT, 0 },
        { "action", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_EXPECTATION_ACTION, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_EXPECTATION_RESTRICTION, 0 },
        { "ext_action", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "severity", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_EXPECTATION_SEVERITY, 0 },
};

const children_list_t iodef_record_pattern_children_list[] = {
        { "offsetunit", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_RECORD_PATTERN_OFFSETUNIT, 0 },
        { "instance", 0, 0, IODEF_VALUE_TYPE_UINT32, 0, 0 },
        { "ext_type", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "offset", 0, 0, IODEF_VALUE_TYPE_UINT32, 0, 0 },
        { "ext_offsetunit", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "type", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_RECORD_PATTERN_TYPE, 0 },
};

const children_list_t iodef_record_item_children_list[] = {
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_RECORD_ITEM_RESTRICTION, 0 },
        { "dtype", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_RECORD_ITEM_DTYPE, 0 },
        { "formatid", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "meaning", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "ext_dtype", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "data", 0, 0, IODEF_VALUE_TYPE_DATA, 0, 0 },
};

const children_list_t iodef_application_children_list[] = {
        { "url", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "vendor", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "name", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "family", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "swid", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "patch", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "version", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "configid", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};

const children_list_t iodef_record_data_children_list[] = {
        { "additional_data", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_ADDITIONAL_DATA, 0 },
        { "description", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "record_pattern", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_RECORD_PATTERN, 0 },
        { "date_time", 0, 0, IODEF_VALUE_TYPE_TIME, 0, 0 },
        { "application", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_APPLICATION, 0 },
        { "record_item", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_RECORD_ITEM, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_RECORD_DATA_RESTRICTION, 0 },
};

const children_list_t iodef_record_children_list[] = {
        { "record_data", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_RECORD_DATA, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_RECORD_RESTRICTION, 0 },
};

const children_list_t iodef_reference_children_list[] = {
        { "url", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "description", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "reference_name", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};

const children_list_t iodef_method_children_list[] = {
        { "additional_data", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_ADDITIONAL_DATA, 0 },
        { "description", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "reference", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_REFERENCE, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_METHOD_RESTRICTION, 0 },
};

const children_list_t iodef_time_impact_children_list[] = {
        { "ext_metric", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "duration", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_TIME_IMPACT_DURATION, 0 },
        { "metric", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_TIME_IMPACT_METRIC, 0 },
        { "severity", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_TIME_IMPACT_SEVERITY, 0 },
        { "ext_duration", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};

const children_list_t iodef_impact_children_list[] = {
        { "lang", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_IMPACT_LANG, 0 },
        { "completion", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_IMPACT_COMPLETION, 0 },
        { "type", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_IMPACT_TYPE, 0 },
        { "severity", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_IMPACT_SEVERITY, 0 },
        { "ext_type", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};

const children_list_t iodef_confidence_children_list[] = {
        { "rating", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_CONFIDENCE_RATING, 0 },
};

const children_list_t iodef_monetary_impact_children_list[] = {
        { "currency", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "severity", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_MONETARY_IMPACT_SEVERITY, 0 },
};

const children_list_t iodef_counter_children_list[] = {
        { "duration", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_COUNTER_DURATION, 0 },
        { "type", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_COUNTER_TYPE, 0 },
        { "ext_duration", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "ext_type", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};

const children_list_t iodef_assessment_children_list[] = {
        { "impact", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_IMPACT, 0 },
        { "additional_data", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_ADDITIONAL_DATA, 0 },
        { "confidence", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_CONFIDENCE, 0 },
        { "time_impact", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_TIME_IMPACT, 0 },
        { "monetary_impact", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_MONETARY_IMPACT, 0 },
        { "counter", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_COUNTER, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_ASSESSMENT_RESTRICTION, 0 },
        { "occurrence", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_ASSESSMENT_OCCURRENCE, 0 },
};

const children_list_t iodef_service_children_list[] = {
        { "proto_code", 0, 0, IODEF_VALUE_TYPE_UINT32, 0, 0 },
        { "proto_flags", 0, 0, IODEF_VALUE_TYPE_UINT32, 0, 0 },
        { "portlist", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "application", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_APPLICATION, 0 },
        { "proto_type", 0, 0, IODEF_VALUE_TYPE_UINT32, 0, 0 },
        { "port", 0, 0, IODEF_VALUE_TYPE_UINT32, 0, 0 },
        { "ip_protocol", 0, 0, IODEF_VALUE_TYPE_UINT32, 0, 0 },
};

const children_list_t iodef_address_children_list[] = {
        { "category", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_ADDRESS_CATEGORY, 0 },
        { "vlan_name", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "ext_category", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "vlan_num", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};

const children_list_t iodef_node_role_children_list[] = {
        { "category", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_NODE_ROLE_CATEGORY, 0 },
        { "lang", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_NODE_ROLE_LANG, 0 },
        { "ext_category", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};

const children_list_t iodef_node_children_list[] = {
        { "node_name", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "counter", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_COUNTER, 0 },
        { "date_time", 0, 0, IODEF_VALUE_TYPE_TIME, 0, 0 },
        { "node_role", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_NODE_ROLE, 0 },
        { "location", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "address", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_ADDRESS, 0 },
};

const children_list_t iodef_operating_system_children_list[] = {
        { "url", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "vendor", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "name", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "family", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "swid", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "patch", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "version", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "configid", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};

const children_list_t iodef_system_children_list[] = {
        { "node", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_NODE, 0 },
        { "additional_data", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_ADDITIONAL_DATA, 0 },
        { "description", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "service", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_SERVICE, 0 },
        { "counter", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_COUNTER, 0 },
        { "operating_system", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_OPERATING_SYSTEM, 0 },
        { "category", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_SYSTEM_CATEGORY, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_SYSTEM_RESTRICTION, 0 },
        { "ext_category", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "spoofed", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_SYSTEM_SPOOFED, 0 },
        { "interface", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};

const children_list_t iodef_flow_children_list[] = {
        { "system", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_SYSTEM, 0 },
};

const children_list_t iodef_event_data_children_list[] = {
        { "detect_time", 0, 0, IODEF_VALUE_TYPE_TIME, 0, 0 },
        { "additional_data", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_ADDITIONAL_DATA, 0 },
        { "description", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "flow", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_FLOW, 0 },
        { "expectation", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_EXPECTATION, 0 },
        { "record", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_RECORD, 0 },
        { "contact", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_CONTACT, 0 },
        { "start_time", 0, 0, IODEF_VALUE_TYPE_TIME, 0, 0 },
        { "event_data", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_EVENT_DATA, 0 },
        { "end_time", 0, 0, IODEF_VALUE_TYPE_TIME, 0, 0 },
        { "assessment", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_ASSESSMENT, 0 },
        { "method", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_METHOD, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_EVENT_DATA_RESTRICTION, 0 },
};

const children_list_t iodef_incident_children_list[] = {
        { "detect_time", 0, 0, IODEF_VALUE_TYPE_TIME, 0, 0 },
        { "additional_data", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_ADDITIONAL_DATA, 0 },
        { "end_time", 0, 0, IODEF_VALUE_TYPE_TIME, 0, 0 },
        { "description", 1, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "contact", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_CONTACT, 0 },
        { "alternative_id", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_ALTERNATIVE_ID, 0 },
        { "report_time", 0, 0, IODEF_VALUE_TYPE_TIME, 0, 0 },
        { "start_time", 0, 0, IODEF_VALUE_TYPE_TIME, 0, 0 },
        { "event_data", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_EVENT_DATA, 0 },
        { "related_activity", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_RELATED_ACTIVITY, 0 },
        { "incident_id", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_INCIDENT_ID, 0 },
        { "assessment", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_ASSESSMENT, 0 },
        { "method", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_METHOD, 0 },
        { "history", 0, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_HISTORY, 0 },
        { "lang", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_INCIDENT_LANG, 0 },
        { "restriction", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_INCIDENT_RESTRICTION, 0 },
        { "ext_purpose", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "purpose", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_INCIDENT_PURPOSE, 0 },
};

const children_list_t iodef_document_children_list[] = {
        { "incident", 1, 0, IODEF_VALUE_TYPE_CLASS, IODEF_CLASS_ID_INCIDENT, 0 },
        { "lang", 0, 0, IODEF_VALUE_TYPE_ENUM, IODEF_CLASS_ID_DOCUMENT_LANG, 0 },
        { "formatid", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
        { "version", 0, 0, IODEF_VALUE_TYPE_STRING, 0, 0 },
};


typedef struct {
        const char *name;
        size_t children_list_elem;
        const children_list_t *children_list;
        int (*get_child)(void *ptr, iodef_class_child_id_t child, void **ret);
        int (*new_child)(void *ptr, iodef_class_child_id_t child, int n, void **ret);
        int (*destroy_child)(void *ptr, iodef_class_child_id_t child, int n);
        int (*to_numeric)(const char *name);
        const char *(*to_string)(int val);
        int (*copy)(const void *src, void *dst);
        int (*clone)(const void *src, void **dst);
        int (*compare)(const void *obj1, const void *obj2);
        int (*print)(const void *obj, prelude_io_t *fd);
        int (*print_json)(const void *obj, prelude_io_t *fd);
        int (*print_binary)(const void *obj, prelude_io_t *fd);
        void *(*ref)(void *src);
        void (*destroy)(void *obj);
        prelude_bool_t is_listed;
} object_data_t;


const object_data_t object_data[] = {
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 0 */
        { "additional_data", sizeof(iodef_additional_data_children_list) / sizeof(*iodef_additional_data_children_list), iodef_additional_data_children_list, _iodef_additional_data_get_child, _iodef_additional_data_new_child, _iodef_additional_data_destroy_child, NULL, NULL, (void *) iodef_additional_data_copy, (void *) iodef_additional_data_clone, (void *) iodef_additional_data_compare, (void *) iodef_additional_data_print, (void *) iodef_additional_data_print_json, (void *) iodef_additional_data_write, (void *) iodef_additional_data_ref, (void *) iodef_additional_data_destroy, 1 },/* ID: 1 */
        { "email", sizeof(iodef_email_children_list) / sizeof(*iodef_email_children_list), iodef_email_children_list, _iodef_email_get_child, _iodef_email_new_child, _iodef_email_destroy_child, NULL, NULL, (void *) iodef_email_copy, (void *) iodef_email_clone, (void *) iodef_email_compare, (void *) iodef_email_print, (void *) iodef_email_print_json, (void *) iodef_email_write, (void *) iodef_email_ref, (void *) iodef_email_destroy, 1 },/* ID: 2 */
        { "registry_handle", sizeof(iodef_registry_handle_children_list) / sizeof(*iodef_registry_handle_children_list), iodef_registry_handle_children_list, _iodef_registry_handle_get_child, _iodef_registry_handle_new_child, _iodef_registry_handle_destroy_child, NULL, NULL, (void *) iodef_registry_handle_copy, (void *) iodef_registry_handle_clone, (void *) iodef_registry_handle_compare, (void *) iodef_registry_handle_print, (void *) iodef_registry_handle_print_json, (void *) iodef_registry_handle_write, (void *) iodef_registry_handle_ref, (void *) iodef_registry_handle_destroy, 1 },/* ID: 3 */
        { "postal_address", sizeof(iodef_postal_address_children_list) / sizeof(*iodef_postal_address_children_list), iodef_postal_address_children_list, _iodef_postal_address_get_child, _iodef_postal_address_new_child, _iodef_postal_address_destroy_child, NULL, NULL, (void *) iodef_postal_address_copy, (void *) iodef_postal_address_clone, (void *) iodef_postal_address_compare, (void *) iodef_postal_address_print, (void *) iodef_postal_address_print_json, (void *) iodef_postal_address_write, (void *) iodef_postal_address_ref, (void *) iodef_postal_address_destroy, 0 },/* ID: 4 */
        { "contact", sizeof(iodef_contact_children_list) / sizeof(*iodef_contact_children_list), iodef_contact_children_list, _iodef_contact_get_child, _iodef_contact_new_child, _iodef_contact_destroy_child, NULL, NULL, (void *) iodef_contact_copy, (void *) iodef_contact_clone, (void *) iodef_contact_compare, (void *) iodef_contact_print, (void *) iodef_contact_print_json, (void *) iodef_contact_write, (void *) iodef_contact_ref, (void *) iodef_contact_destroy, 1 },/* ID: 5 */
        { "incident_id", sizeof(iodef_incident_id_children_list) / sizeof(*iodef_incident_id_children_list), iodef_incident_id_children_list, _iodef_incident_id_get_child, _iodef_incident_id_new_child, _iodef_incident_id_destroy_child, NULL, NULL, (void *) iodef_incident_id_copy, (void *) iodef_incident_id_clone, (void *) iodef_incident_id_compare, (void *) iodef_incident_id_print, (void *) iodef_incident_id_print_json, (void *) iodef_incident_id_write, (void *) iodef_incident_id_ref, (void *) iodef_incident_id_destroy, 1 },/* ID: 6 */
        { "alternative_id", sizeof(iodef_alternative_id_children_list) / sizeof(*iodef_alternative_id_children_list), iodef_alternative_id_children_list, _iodef_alternative_id_get_child, _iodef_alternative_id_new_child, _iodef_alternative_id_destroy_child, NULL, NULL, (void *) iodef_alternative_id_copy, (void *) iodef_alternative_id_clone, (void *) iodef_alternative_id_compare, (void *) iodef_alternative_id_print, (void *) iodef_alternative_id_print_json, (void *) iodef_alternative_id_write, (void *) iodef_alternative_id_ref, (void *) iodef_alternative_id_destroy, 0 },/* ID: 7 */
        { "related_activity", sizeof(iodef_related_activity_children_list) / sizeof(*iodef_related_activity_children_list), iodef_related_activity_children_list, _iodef_related_activity_get_child, _iodef_related_activity_new_child, _iodef_related_activity_destroy_child, NULL, NULL, (void *) iodef_related_activity_copy, (void *) iodef_related_activity_clone, (void *) iodef_related_activity_compare, (void *) iodef_related_activity_print, (void *) iodef_related_activity_print_json, (void *) iodef_related_activity_write, (void *) iodef_related_activity_ref, (void *) iodef_related_activity_destroy, 0 },/* ID: 8 */
        { "history_item", sizeof(iodef_history_item_children_list) / sizeof(*iodef_history_item_children_list), iodef_history_item_children_list, _iodef_history_item_get_child, _iodef_history_item_new_child, _iodef_history_item_destroy_child, NULL, NULL, (void *) iodef_history_item_copy, (void *) iodef_history_item_clone, (void *) iodef_history_item_compare, (void *) iodef_history_item_print, (void *) iodef_history_item_print_json, (void *) iodef_history_item_write, (void *) iodef_history_item_ref, (void *) iodef_history_item_destroy, 1 },/* ID: 9 */
        { "history", sizeof(iodef_history_children_list) / sizeof(*iodef_history_children_list), iodef_history_children_list, _iodef_history_get_child, _iodef_history_new_child, _iodef_history_destroy_child, NULL, NULL, (void *) iodef_history_copy, (void *) iodef_history_clone, (void *) iodef_history_compare, (void *) iodef_history_print, (void *) iodef_history_print_json, (void *) iodef_history_write, (void *) iodef_history_ref, (void *) iodef_history_destroy, 0 },/* ID: 10 */
        { "expectation", sizeof(iodef_expectation_children_list) / sizeof(*iodef_expectation_children_list), iodef_expectation_children_list, _iodef_expectation_get_child, _iodef_expectation_new_child, _iodef_expectation_destroy_child, NULL, NULL, (void *) iodef_expectation_copy, (void *) iodef_expectation_clone, (void *) iodef_expectation_compare, (void *) iodef_expectation_print, (void *) iodef_expectation_print_json, (void *) iodef_expectation_write, (void *) iodef_expectation_ref, (void *) iodef_expectation_destroy, 1 },/* ID: 11 */
        { "record_pattern", sizeof(iodef_record_pattern_children_list) / sizeof(*iodef_record_pattern_children_list), iodef_record_pattern_children_list, _iodef_record_pattern_get_child, _iodef_record_pattern_new_child, _iodef_record_pattern_destroy_child, NULL, NULL, (void *) iodef_record_pattern_copy, (void *) iodef_record_pattern_clone, (void *) iodef_record_pattern_compare, (void *) iodef_record_pattern_print, (void *) iodef_record_pattern_print_json, (void *) iodef_record_pattern_write, (void *) iodef_record_pattern_ref, (void *) iodef_record_pattern_destroy, 1 },/* ID: 12 */
        { "record_item", sizeof(iodef_record_item_children_list) / sizeof(*iodef_record_item_children_list), iodef_record_item_children_list, _iodef_record_item_get_child, _iodef_record_item_new_child, _iodef_record_item_destroy_child, NULL, NULL, (void *) iodef_record_item_copy, (void *) iodef_record_item_clone, (void *) iodef_record_item_compare, (void *) iodef_record_item_print, (void *) iodef_record_item_print_json, (void *) iodef_record_item_write, (void *) iodef_record_item_ref, (void *) iodef_record_item_destroy, 1 },/* ID: 13 */
        { "application", sizeof(iodef_application_children_list) / sizeof(*iodef_application_children_list), iodef_application_children_list, _iodef_application_get_child, _iodef_application_new_child, _iodef_application_destroy_child, NULL, NULL, (void *) iodef_application_copy, (void *) iodef_application_clone, (void *) iodef_application_compare, (void *) iodef_application_print, (void *) iodef_application_print_json, (void *) iodef_application_write, (void *) iodef_application_ref, (void *) iodef_application_destroy, 1 },/* ID: 14 */
        { "record_data", sizeof(iodef_record_data_children_list) / sizeof(*iodef_record_data_children_list), iodef_record_data_children_list, _iodef_record_data_get_child, _iodef_record_data_new_child, _iodef_record_data_destroy_child, NULL, NULL, (void *) iodef_record_data_copy, (void *) iodef_record_data_clone, (void *) iodef_record_data_compare, (void *) iodef_record_data_print, (void *) iodef_record_data_print_json, (void *) iodef_record_data_write, (void *) iodef_record_data_ref, (void *) iodef_record_data_destroy, 1 },/* ID: 15 */
        { "record", sizeof(iodef_record_children_list) / sizeof(*iodef_record_children_list), iodef_record_children_list, _iodef_record_get_child, _iodef_record_new_child, _iodef_record_destroy_child, NULL, NULL, (void *) iodef_record_copy, (void *) iodef_record_clone, (void *) iodef_record_compare, (void *) iodef_record_print, (void *) iodef_record_print_json, (void *) iodef_record_write, (void *) iodef_record_ref, (void *) iodef_record_destroy, 0 },/* ID: 16 */
        { "reference", sizeof(iodef_reference_children_list) / sizeof(*iodef_reference_children_list), iodef_reference_children_list, _iodef_reference_get_child, _iodef_reference_new_child, _iodef_reference_destroy_child, NULL, NULL, (void *) iodef_reference_copy, (void *) iodef_reference_clone, (void *) iodef_reference_compare, (void *) iodef_reference_print, (void *) iodef_reference_print_json, (void *) iodef_reference_write, (void *) iodef_reference_ref, (void *) iodef_reference_destroy, 1 },/* ID: 17 */
        { "method", sizeof(iodef_method_children_list) / sizeof(*iodef_method_children_list), iodef_method_children_list, _iodef_method_get_child, _iodef_method_new_child, _iodef_method_destroy_child, NULL, NULL, (void *) iodef_method_copy, (void *) iodef_method_clone, (void *) iodef_method_compare, (void *) iodef_method_print, (void *) iodef_method_print_json, (void *) iodef_method_write, (void *) iodef_method_ref, (void *) iodef_method_destroy, 1 },/* ID: 18 */
        { "time_impact", sizeof(iodef_time_impact_children_list) / sizeof(*iodef_time_impact_children_list), iodef_time_impact_children_list, _iodef_time_impact_get_child, _iodef_time_impact_new_child, _iodef_time_impact_destroy_child, NULL, NULL, (void *) iodef_time_impact_copy, (void *) iodef_time_impact_clone, (void *) iodef_time_impact_compare, (void *) iodef_time_impact_print, (void *) iodef_time_impact_print_json, (void *) iodef_time_impact_write, (void *) iodef_time_impact_ref, (void *) iodef_time_impact_destroy, 1 },/* ID: 19 */
        { "impact", sizeof(iodef_impact_children_list) / sizeof(*iodef_impact_children_list), iodef_impact_children_list, _iodef_impact_get_child, _iodef_impact_new_child, _iodef_impact_destroy_child, NULL, NULL, (void *) iodef_impact_copy, (void *) iodef_impact_clone, (void *) iodef_impact_compare, (void *) iodef_impact_print, (void *) iodef_impact_print_json, (void *) iodef_impact_write, (void *) iodef_impact_ref, (void *) iodef_impact_destroy, 1 },/* ID: 20 */
        { "confidence", sizeof(iodef_confidence_children_list) / sizeof(*iodef_confidence_children_list), iodef_confidence_children_list, _iodef_confidence_get_child, _iodef_confidence_new_child, _iodef_confidence_destroy_child, NULL, NULL, (void *) iodef_confidence_copy, (void *) iodef_confidence_clone, (void *) iodef_confidence_compare, (void *) iodef_confidence_print, (void *) iodef_confidence_print_json, (void *) iodef_confidence_write, (void *) iodef_confidence_ref, (void *) iodef_confidence_destroy, 0 },/* ID: 21 */
        { "monetary_impact", sizeof(iodef_monetary_impact_children_list) / sizeof(*iodef_monetary_impact_children_list), iodef_monetary_impact_children_list, _iodef_monetary_impact_get_child, _iodef_monetary_impact_new_child, _iodef_monetary_impact_destroy_child, NULL, NULL, (void *) iodef_monetary_impact_copy, (void *) iodef_monetary_impact_clone, (void *) iodef_monetary_impact_compare, (void *) iodef_monetary_impact_print, (void *) iodef_monetary_impact_print_json, (void *) iodef_monetary_impact_write, (void *) iodef_monetary_impact_ref, (void *) iodef_monetary_impact_destroy, 1 },/* ID: 22 */
        { "counter", sizeof(iodef_counter_children_list) / sizeof(*iodef_counter_children_list), iodef_counter_children_list, _iodef_counter_get_child, _iodef_counter_new_child, _iodef_counter_destroy_child, NULL, NULL, (void *) iodef_counter_copy, (void *) iodef_counter_clone, (void *) iodef_counter_compare, (void *) iodef_counter_print, (void *) iodef_counter_print_json, (void *) iodef_counter_write, (void *) iodef_counter_ref, (void *) iodef_counter_destroy, 1 },/* ID: 23 */
        { "assessment", sizeof(iodef_assessment_children_list) / sizeof(*iodef_assessment_children_list), iodef_assessment_children_list, _iodef_assessment_get_child, _iodef_assessment_new_child, _iodef_assessment_destroy_child, NULL, NULL, (void *) iodef_assessment_copy, (void *) iodef_assessment_clone, (void *) iodef_assessment_compare, (void *) iodef_assessment_print, (void *) iodef_assessment_print_json, (void *) iodef_assessment_write, (void *) iodef_assessment_ref, (void *) iodef_assessment_destroy, 1 },/* ID: 24 */
        { "service", sizeof(iodef_service_children_list) / sizeof(*iodef_service_children_list), iodef_service_children_list, _iodef_service_get_child, _iodef_service_new_child, _iodef_service_destroy_child, NULL, NULL, (void *) iodef_service_copy, (void *) iodef_service_clone, (void *) iodef_service_compare, (void *) iodef_service_print, (void *) iodef_service_print_json, (void *) iodef_service_write, (void *) iodef_service_ref, (void *) iodef_service_destroy, 1 },/* ID: 25 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 26 */
        { "address", sizeof(iodef_address_children_list) / sizeof(*iodef_address_children_list), iodef_address_children_list, _iodef_address_get_child, _iodef_address_new_child, _iodef_address_destroy_child, NULL, NULL, (void *) iodef_address_copy, (void *) iodef_address_clone, (void *) iodef_address_compare, (void *) iodef_address_print, (void *) iodef_address_print_json, (void *) iodef_address_write, (void *) iodef_address_ref, (void *) iodef_address_destroy, 1 },/* ID: 27 */
        { "node_role", sizeof(iodef_node_role_children_list) / sizeof(*iodef_node_role_children_list), iodef_node_role_children_list, _iodef_node_role_get_child, _iodef_node_role_new_child, _iodef_node_role_destroy_child, NULL, NULL, (void *) iodef_node_role_copy, (void *) iodef_node_role_clone, (void *) iodef_node_role_compare, (void *) iodef_node_role_print, (void *) iodef_node_role_print_json, (void *) iodef_node_role_write, (void *) iodef_node_role_ref, (void *) iodef_node_role_destroy, 1 },/* ID: 28 */
        { "node", sizeof(iodef_node_children_list) / sizeof(*iodef_node_children_list), iodef_node_children_list, _iodef_node_get_child, _iodef_node_new_child, _iodef_node_destroy_child, NULL, NULL, (void *) iodef_node_copy, (void *) iodef_node_clone, (void *) iodef_node_compare, (void *) iodef_node_print, (void *) iodef_node_print_json, (void *) iodef_node_write, (void *) iodef_node_ref, (void *) iodef_node_destroy, 0 },/* ID: 29 */
        { "operating_system", sizeof(iodef_operating_system_children_list) / sizeof(*iodef_operating_system_children_list), iodef_operating_system_children_list, _iodef_operating_system_get_child, _iodef_operating_system_new_child, _iodef_operating_system_destroy_child, NULL, NULL, (void *) iodef_operating_system_copy, (void *) iodef_operating_system_clone, (void *) iodef_operating_system_compare, (void *) iodef_operating_system_print, (void *) iodef_operating_system_print_json, (void *) iodef_operating_system_write, (void *) iodef_operating_system_ref, (void *) iodef_operating_system_destroy, 0 },/* ID: 30 */
        { "system", sizeof(iodef_system_children_list) / sizeof(*iodef_system_children_list), iodef_system_children_list, _iodef_system_get_child, _iodef_system_new_child, _iodef_system_destroy_child, NULL, NULL, (void *) iodef_system_copy, (void *) iodef_system_clone, (void *) iodef_system_compare, (void *) iodef_system_print, (void *) iodef_system_print_json, (void *) iodef_system_write, (void *) iodef_system_ref, (void *) iodef_system_destroy, 1 },/* ID: 31 */
        { "flow", sizeof(iodef_flow_children_list) / sizeof(*iodef_flow_children_list), iodef_flow_children_list, _iodef_flow_get_child, _iodef_flow_new_child, _iodef_flow_destroy_child, NULL, NULL, (void *) iodef_flow_copy, (void *) iodef_flow_clone, (void *) iodef_flow_compare, (void *) iodef_flow_print, (void *) iodef_flow_print_json, (void *) iodef_flow_write, (void *) iodef_flow_ref, (void *) iodef_flow_destroy, 1 },/* ID: 32 */
        { "event_data", sizeof(iodef_event_data_children_list) / sizeof(*iodef_event_data_children_list), iodef_event_data_children_list, _iodef_event_data_get_child, _iodef_event_data_new_child, _iodef_event_data_destroy_child, NULL, NULL, (void *) iodef_event_data_copy, (void *) iodef_event_data_clone, (void *) iodef_event_data_compare, (void *) iodef_event_data_print, (void *) iodef_event_data_print_json, (void *) iodef_event_data_write, (void *) iodef_event_data_ref, (void *) iodef_event_data_destroy, 1 },/* ID: 33 */
        { "incident", sizeof(iodef_incident_children_list) / sizeof(*iodef_incident_children_list), iodef_incident_children_list, _iodef_incident_get_child, _iodef_incident_new_child, _iodef_incident_destroy_child, NULL, NULL, (void *) iodef_incident_copy, (void *) iodef_incident_clone, (void *) iodef_incident_compare, (void *) iodef_incident_print, (void *) iodef_incident_print_json, (void *) iodef_incident_write, (void *) iodef_incident_ref, (void *) iodef_incident_destroy, 1 },/* ID: 34 */
        { "document", sizeof(iodef_document_children_list) / sizeof(*iodef_document_children_list), iodef_document_children_list, _iodef_document_get_child, _iodef_document_new_child, _iodef_document_destroy_child, NULL, NULL, (void *) iodef_document_copy, (void *) iodef_document_clone, (void *) iodef_document_compare, (void *) iodef_document_print, (void *) iodef_document_print_json, (void *) iodef_document_write, (void *) iodef_document_ref, (void *) iodef_document_destroy, 0 },/* ID: 35 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 36 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 37 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 38 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 39 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 40 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 41 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 42 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 43 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 44 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 45 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 46 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 47 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 48 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 49 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 50 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 51 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 52 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 53 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 54 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 55 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 56 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 57 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 58 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 59 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 60 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 61 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 62 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 63 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 64 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 65 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 66 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 67 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 68 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 69 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 70 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 71 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 72 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 73 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 74 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 75 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 76 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 77 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 78 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 79 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 80 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 81 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 82 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 83 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 84 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 85 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 86 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 87 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 88 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 89 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 90 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 91 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 92 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 93 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 94 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 95 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 96 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 97 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 98 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 99 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 100 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 101 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 102 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 103 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 104 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 105 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 106 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 107 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 108 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 109 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 110 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 111 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 112 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 113 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 114 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 115 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 116 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 117 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 118 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 119 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 120 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 121 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 122 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 123 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 124 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 125 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 126 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 127 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 128 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 129 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 130 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 131 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 132 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 133 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 134 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 135 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 136 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 137 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 138 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 139 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 140 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 141 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 142 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 143 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 144 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 145 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 146 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 147 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 148 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 149 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 150 */
        { "additional_data_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_additional_data_restriction_to_numeric, (void *) iodef_additional_data_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 151 */
        { "additional_data_type", 0, NULL, NULL, NULL, NULL, (void *) iodef_additional_data_type_to_numeric, (void *) iodef_additional_data_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 152 */
        { "email_meaning", 0, NULL, NULL, NULL, NULL, (void *) iodef_email_meaning_to_numeric, (void *) iodef_email_meaning_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 153 */
        { "registry_handle_registry", 0, NULL, NULL, NULL, NULL, (void *) iodef_registry_handle_registry_to_numeric, (void *) iodef_registry_handle_registry_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 154 */
        { "postal_address_lang", 0, NULL, NULL, NULL, NULL, (void *) iodef_postal_address_lang_to_numeric, (void *) iodef_postal_address_lang_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 155 */
        { "postal_address_meaning", 0, NULL, NULL, NULL, NULL, (void *) iodef_postal_address_meaning_to_numeric, (void *) iodef_postal_address_meaning_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 156 */
        { "contact_type", 0, NULL, NULL, NULL, NULL, (void *) iodef_contact_type_to_numeric, (void *) iodef_contact_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 157 */
        { "contact_role", 0, NULL, NULL, NULL, NULL, (void *) iodef_contact_role_to_numeric, (void *) iodef_contact_role_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 158 */
        { "contact_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_contact_restriction_to_numeric, (void *) iodef_contact_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 159 */
        { "incident_id_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_incident_id_restriction_to_numeric, (void *) iodef_incident_id_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 160 */
        { "alternative_id_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_alternative_id_restriction_to_numeric, (void *) iodef_alternative_id_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 161 */
        { "related_activity_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_related_activity_restriction_to_numeric, (void *) iodef_related_activity_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 162 */
        { "history_item_action", 0, NULL, NULL, NULL, NULL, (void *) iodef_history_item_action_to_numeric, (void *) iodef_history_item_action_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 163 */
        { "history_item_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_history_item_restriction_to_numeric, (void *) iodef_history_item_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 164 */
        { "history_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_history_restriction_to_numeric, (void *) iodef_history_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 165 */
        { "expectation_action", 0, NULL, NULL, NULL, NULL, (void *) iodef_expectation_action_to_numeric, (void *) iodef_expectation_action_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 166 */
        { "expectation_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_expectation_restriction_to_numeric, (void *) iodef_expectation_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 167 */
        { "expectation_severity", 0, NULL, NULL, NULL, NULL, (void *) iodef_expectation_severity_to_numeric, (void *) iodef_expectation_severity_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 168 */
        { "record_pattern_offsetunit", 0, NULL, NULL, NULL, NULL, (void *) iodef_record_pattern_offsetunit_to_numeric, (void *) iodef_record_pattern_offsetunit_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 169 */
        { "record_pattern_type", 0, NULL, NULL, NULL, NULL, (void *) iodef_record_pattern_type_to_numeric, (void *) iodef_record_pattern_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 170 */
        { "record_item_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_record_item_restriction_to_numeric, (void *) iodef_record_item_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 171 */
        { "record_item_dtype", 0, NULL, NULL, NULL, NULL, (void *) iodef_record_item_dtype_to_numeric, (void *) iodef_record_item_dtype_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 172 */
        { "record_data_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_record_data_restriction_to_numeric, (void *) iodef_record_data_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 173 */
        { "record_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_record_restriction_to_numeric, (void *) iodef_record_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 174 */
        { "method_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_method_restriction_to_numeric, (void *) iodef_method_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 175 */
        { "time_impact_duration", 0, NULL, NULL, NULL, NULL, (void *) iodef_time_impact_duration_to_numeric, (void *) iodef_time_impact_duration_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 176 */
        { "time_impact_metric", 0, NULL, NULL, NULL, NULL, (void *) iodef_time_impact_metric_to_numeric, (void *) iodef_time_impact_metric_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 177 */
        { "time_impact_severity", 0, NULL, NULL, NULL, NULL, (void *) iodef_time_impact_severity_to_numeric, (void *) iodef_time_impact_severity_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 178 */
        { "impact_lang", 0, NULL, NULL, NULL, NULL, (void *) iodef_impact_lang_to_numeric, (void *) iodef_impact_lang_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 179 */
        { "impact_completion", 0, NULL, NULL, NULL, NULL, (void *) iodef_impact_completion_to_numeric, (void *) iodef_impact_completion_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 180 */
        { "impact_type", 0, NULL, NULL, NULL, NULL, (void *) iodef_impact_type_to_numeric, (void *) iodef_impact_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 181 */
        { "impact_severity", 0, NULL, NULL, NULL, NULL, (void *) iodef_impact_severity_to_numeric, (void *) iodef_impact_severity_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 182 */
        { "confidence_rating", 0, NULL, NULL, NULL, NULL, (void *) iodef_confidence_rating_to_numeric, (void *) iodef_confidence_rating_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 183 */
        { "monetary_impact_severity", 0, NULL, NULL, NULL, NULL, (void *) iodef_monetary_impact_severity_to_numeric, (void *) iodef_monetary_impact_severity_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 184 */
        { "counter_duration", 0, NULL, NULL, NULL, NULL, (void *) iodef_counter_duration_to_numeric, (void *) iodef_counter_duration_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 185 */
        { "counter_type", 0, NULL, NULL, NULL, NULL, (void *) iodef_counter_type_to_numeric, (void *) iodef_counter_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 186 */
        { "assessment_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_assessment_restriction_to_numeric, (void *) iodef_assessment_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 187 */
        { "assessment_occurrence", 0, NULL, NULL, NULL, NULL, (void *) iodef_assessment_occurrence_to_numeric, (void *) iodef_assessment_occurrence_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 188 */
        { "address_category", 0, NULL, NULL, NULL, NULL, (void *) iodef_address_category_to_numeric, (void *) iodef_address_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 189 */
        { "node_role_category", 0, NULL, NULL, NULL, NULL, (void *) iodef_node_role_category_to_numeric, (void *) iodef_node_role_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 190 */
        { "node_role_lang", 0, NULL, NULL, NULL, NULL, (void *) iodef_node_role_lang_to_numeric, (void *) iodef_node_role_lang_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 191 */
        { "system_category", 0, NULL, NULL, NULL, NULL, (void *) iodef_system_category_to_numeric, (void *) iodef_system_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 192 */
        { "system_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_system_restriction_to_numeric, (void *) iodef_system_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 193 */
        { "system_spoofed", 0, NULL, NULL, NULL, NULL, (void *) iodef_system_spoofed_to_numeric, (void *) iodef_system_spoofed_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 194 */
        { "event_data_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_event_data_restriction_to_numeric, (void *) iodef_event_data_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 195 */
        { "incident_lang", 0, NULL, NULL, NULL, NULL, (void *) iodef_incident_lang_to_numeric, (void *) iodef_incident_lang_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 196 */
        { "incident_restriction", 0, NULL, NULL, NULL, NULL, (void *) iodef_incident_restriction_to_numeric, (void *) iodef_incident_restriction_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 197 */
        { "incident_purpose", 0, NULL, NULL, NULL, NULL, (void *) iodef_incident_purpose_to_numeric, (void *) iodef_incident_purpose_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 198 */
        { "document_lang", 0, NULL, NULL, NULL, NULL, (void *) iodef_document_lang_to_numeric, (void *) iodef_document_lang_to_string, NULL, NULL, NULL, NULL, NULL, 0 }, /* ID: 199 */
        { NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }
};
