
/*****
*
* Copyright (C) 2001-2016 CS-SI. All Rights Reserved.
* Author: Yoann Vandoorselaere <yoann.v@libiodef-ids.com>
*
* This file is part of the LibIodef library.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*
*****/

/* Auto-generated by the GenerateIODEFMessageWriteH package */

#ifndef _LIBIODEF_IODEF_DOCUMENT_WRITE_H
#define _LIBIODEF_IODEF_DOCUMENT_WRITE_H

#include "libiodef-inttypes.h"
#include "iodef-time.h"
#include "libiodef-string.h"
#include "libiodef-io.h"

#ifdef __cplusplus
 extern "C" {
#endif

int iodef_additional_data_write(iodef_additional_data_t *additional_data, libiodef_io_t *fd);
int iodef_email_write(iodef_email_t *email, libiodef_io_t *fd);
int iodef_registry_handle_write(iodef_registry_handle_t *registry_handle, libiodef_io_t *fd);
int iodef_postal_address_write(iodef_postal_address_t *postal_address, libiodef_io_t *fd);
int iodef_contact_write(iodef_contact_t *contact, libiodef_io_t *fd);
int iodef_incident_id_write(iodef_incident_id_t *incident_id, libiodef_io_t *fd);
int iodef_alternative_id_write(iodef_alternative_id_t *alternative_id, libiodef_io_t *fd);
int iodef_related_activity_write(iodef_related_activity_t *related_activity, libiodef_io_t *fd);
int iodef_history_item_write(iodef_history_item_t *history_item, libiodef_io_t *fd);
int iodef_history_write(iodef_history_t *history, libiodef_io_t *fd);
int iodef_expectation_write(iodef_expectation_t *expectation, libiodef_io_t *fd);
int iodef_record_pattern_write(iodef_record_pattern_t *record_pattern, libiodef_io_t *fd);
int iodef_record_item_write(iodef_record_item_t *record_item, libiodef_io_t *fd);
int iodef_application_write(iodef_application_t *application, libiodef_io_t *fd);
int iodef_record_data_write(iodef_record_data_t *record_data, libiodef_io_t *fd);
int iodef_record_write(iodef_record_t *record, libiodef_io_t *fd);
int iodef_reference_write(iodef_reference_t *reference, libiodef_io_t *fd);
int iodef_method_write(iodef_method_t *method, libiodef_io_t *fd);
int iodef_time_impact_write(iodef_time_impact_t *time_impact, libiodef_io_t *fd);
int iodef_impact_write(iodef_impact_t *impact, libiodef_io_t *fd);
int iodef_confidence_write(iodef_confidence_t *confidence, libiodef_io_t *fd);
int iodef_monetary_impact_write(iodef_monetary_impact_t *monetary_impact, libiodef_io_t *fd);
int iodef_counter_write(iodef_counter_t *counter, libiodef_io_t *fd);
int iodef_assessment_write(iodef_assessment_t *assessment, libiodef_io_t *fd);
int iodef_service_write(iodef_service_t *service, libiodef_io_t *fd);
int iodef_address_write(iodef_address_t *address, libiodef_io_t *fd);
int iodef_node_role_write(iodef_node_role_t *node_role, libiodef_io_t *fd);
int iodef_node_write(iodef_node_t *node, libiodef_io_t *fd);
int iodef_operating_system_write(iodef_operating_system_t *operating_system, libiodef_io_t *fd);
int iodef_system_write(iodef_system_t *system, libiodef_io_t *fd);
int iodef_flow_write(iodef_flow_t *flow, libiodef_io_t *fd);
int iodef_event_data_write(iodef_event_data_t *event_data, libiodef_io_t *fd);
int iodef_incident_write(iodef_incident_t *incident, libiodef_io_t *fd);
int iodef_document_write(iodef_document_t *document, libiodef_io_t *fd);


#ifdef __cplusplus
 }
#endif

#endif /* _LIBIODEF_IODEF_DOCUMENT_WRITE_H */
