
/*****
*
* Copyright (C) 2003-2016 CS-SI. All Rights Reserved.
* Author: Yoann Vandoorselaere <yoann.v@libiodef-ids.com>
*
* This file is part of the LibIodef library.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*
*****/

/* Auto-generated by the GenerateIODEFTreePrintH package */

#ifndef _LIBIODEF_IODEF_DOCUMENT_PRINT_H
#define _LIBIODEF_IODEF_DOCUMENT_PRINT_H

#ifdef __cplusplus
 extern "C" {
#endif


void iodef_additional_data_print(iodef_additional_data_t *ptr, libiodef_io_t *fd);
void iodef_email_print(iodef_email_t *ptr, libiodef_io_t *fd);
void iodef_registry_handle_print(iodef_registry_handle_t *ptr, libiodef_io_t *fd);
void iodef_postal_address_print(iodef_postal_address_t *ptr, libiodef_io_t *fd);
void iodef_contact_print(iodef_contact_t *ptr, libiodef_io_t *fd);
void iodef_incident_id_print(iodef_incident_id_t *ptr, libiodef_io_t *fd);
void iodef_alternative_id_print(iodef_alternative_id_t *ptr, libiodef_io_t *fd);
void iodef_related_activity_print(iodef_related_activity_t *ptr, libiodef_io_t *fd);
void iodef_history_item_print(iodef_history_item_t *ptr, libiodef_io_t *fd);
void iodef_history_print(iodef_history_t *ptr, libiodef_io_t *fd);
void iodef_expectation_print(iodef_expectation_t *ptr, libiodef_io_t *fd);
void iodef_record_pattern_print(iodef_record_pattern_t *ptr, libiodef_io_t *fd);
void iodef_record_item_print(iodef_record_item_t *ptr, libiodef_io_t *fd);
void iodef_application_print(iodef_application_t *ptr, libiodef_io_t *fd);
void iodef_record_data_print(iodef_record_data_t *ptr, libiodef_io_t *fd);
void iodef_record_print(iodef_record_t *ptr, libiodef_io_t *fd);
void iodef_reference_print(iodef_reference_t *ptr, libiodef_io_t *fd);
void iodef_method_print(iodef_method_t *ptr, libiodef_io_t *fd);
void iodef_time_impact_print(iodef_time_impact_t *ptr, libiodef_io_t *fd);
void iodef_impact_print(iodef_impact_t *ptr, libiodef_io_t *fd);
void iodef_confidence_print(iodef_confidence_t *ptr, libiodef_io_t *fd);
void iodef_monetary_impact_print(iodef_monetary_impact_t *ptr, libiodef_io_t *fd);
void iodef_counter_print(iodef_counter_t *ptr, libiodef_io_t *fd);
void iodef_assessment_print(iodef_assessment_t *ptr, libiodef_io_t *fd);
void iodef_service_print(iodef_service_t *ptr, libiodef_io_t *fd);
void iodef_address_print(iodef_address_t *ptr, libiodef_io_t *fd);
void iodef_node_role_print(iodef_node_role_t *ptr, libiodef_io_t *fd);
void iodef_node_print(iodef_node_t *ptr, libiodef_io_t *fd);
void iodef_operating_system_print(iodef_operating_system_t *ptr, libiodef_io_t *fd);
void iodef_system_print(iodef_system_t *ptr, libiodef_io_t *fd);
void iodef_flow_print(iodef_flow_t *ptr, libiodef_io_t *fd);
void iodef_event_data_print(iodef_event_data_t *ptr, libiodef_io_t *fd);
void iodef_incident_print(iodef_incident_t *ptr, libiodef_io_t *fd);
void iodef_document_print(iodef_document_t *ptr, libiodef_io_t *fd);

#ifdef __cplusplus
 }
#endif

#endif /* _LIBIODEF_IODEF_DOCUMENT_PRINT_H */
